[package]
name = "evolution-mocker"
version = "1.0.0"
description = "Mocking components of evolution."
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[dependencies]
evolution-common = { path = "../evolution-common" }
evolution-schema = { path = "../evolution-schema" }
evolution-writer = { path = "../evolution-writer" }
log = "0.4.21"
