[workspace]
members = []
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://github.com/firelink-data/evolution"
repository = "https://github.com/firelink-data/evolution"
authors = [
    "Wilhelm Ågren <wilhelmagren98@gmail.com>",
    "Rickard Lundin <rickard@x14.se>",
    "Ted Hammarlund <TedHammarlund@gmail.com>",
]
license = "MIT"
version = "1.3.0"
readme = "README.md"
categories = [
    "science",
    "database",
    "concurrency",
    "command-line-interface",
]
keywords = [
    "arrow",
    "parquet",
    "concurrency",
    "data-engineering",
    "ETL",
]
description = "Efficiently evolve your old fixed-length data files into modern file formats."

[workspace.dependencies]