[package]
name = "evolution-writer"
version = "1.0.0"
description = "Output writers for evolution."
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[dependencies]
arrow = "51.0.0"
evolution-builder = { path = "../evolution-builder", version = "1.0.0" }
evolution-common = { path = "../evolution-common", version = "1.0.0" }
parquet = "51.0.0"
